log_dir: "Models/run"
save_freq: 1
log_interval: 10
save_interval: 10000
device: "cuda"
epochs: 1000 # number of epochs for first stage training (pre-training)
batch_size: 64
batch_length: 100 # maximum duration of audio in a batch (in seconds)
max_len: 80 # maximum number of frames
pretrained_model: ""
load_only_params: False # set to true if do not want to load epoch numbers and optimizer parameters

F0_path: "modules/JDC/bst.t7"

data_params:
  train_data: "./data/train.txt"
  val_data: "./data/val.txt"
  root_path: "./data/"

preprocess_params:
  sr: 16000
  spect_params:
    n_fft: 1024
    win_length: 800
    hop_length: 200

model_params:
  fixed: True

loss_params:
  base_lr: 0.0001
  discriminator_iter_start: 2000
  lambda_spk: 1.0
  lambda_mel: 45
  lambda_f0: 1.0
  lambda_uv: 1.0
